name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git fetch https://rizkisyaf:$HF_TOKEN@huggingface.co/spaces/rizkisyaf/zdml main
          git pull https://rizkisyaf:$HF_TOKEN@huggingface.co/spaces/rizkisyaf/zdml main --allow-unrelated-histories || true
          git push https://rizkisyaf:$HF_TOKEN@huggingface.co/spaces/rizkisyaf/zdml main 